@startuml

object get_transaction
object _buy_plane
object _buy_gun

object get_hangar
object get_buyer
object get_account

class Shop {
+ db
{abstract} + buy_plane()
{abstract} + buy_gun()
}
class WarPlanesShop {
+ buy_plane()
+ buy_gun()
- _product_spec_by_id()
- _product_price_by_id()
# __compatible_guns()
# __update_player()
}
class Buyer {
+ id
+ account
+ hangar
}
class Account {
+ account
+ decrease()
+ has_enought_resource()
+ as_dict()
}
class Hangar {
+ planes
+ add_plane()
+ has_plane()
+ current_weapon()
+ set_weapon()
+ as_dict()
}
class Transaction {
- _transaction_strategy
+ transaction
+ commit()
}
Shop <|-- WarPlanesShop
Account <-- get_account
Hangar <-- get_hangar
Transaction <- get_transaction
Buyer <-- get_buyer
Buyer --> get_account
Buyer --> get_hangar
Buyer o..> Account
Buyer o..> Hangar
WarPlanesShop -> get_buyer
WarPlanesShop --> get_transaction
WarPlanesShop o.. Buyer
WarPlanesShop o.. Transaction
_buy_plane - get_transaction
_buy_gun - get_transaction

@enduml