@startuml
class Exception
class ShopError
class TransactionError
class TransactionValidationError
class MessageValidationError
class ProductDatabaseError


Exception <|-- ShopError
ShopError <|-- TransactionError
ShopError <|-- ProductDatabaseError
TransactionError <|-- TransactionValidationError
TransactionError <|-- MessageValidationError
hide members
@enduml