@startuml
class Exception
class ShopErrors
class TransactionValidationError
class ProductsNotCompatible
class ProductAlreadyBoat
class NotEnoughtResources
class NoSuchPlaneInHangar

Exception <|-- ShopErrors
ShopErrors <|-- TransactionValidationError
TransactionValidationError <|-- ProductsNotCompatible
TransactionValidationError <|-- ProductAlreadyBoat
TransactionValidationError <|-- NotEnoughtResources
TransactionValidationError <|-- NoSuchPlaneInHangar
hide members
@enduml